### ISSUE TITLE
Column Grouping in GigaGrid

### ISSUE THREAD

**Issue by erfangc** [erfangc/GigaGrid#14]
We should leverage `tr > th[col-span]` features of the HTML table spec and allow users to decorate column headers with additional layers of headers

we need to decide on the input format we would accept from the user and then just render them as additional `tr` in the `header` with the appropriate col-spans

**Comment by erfangc** [comment]
@shriniwasayyer14 hey, you have requested this feature. what is the best way in your opinion for the user to specify column groups?

I can think of two approaches,

## 1. as a single object to the `columnDefs` props

``` json
{
    "group_1": {
         "title": "Group 1 Title",
         "columnDefs": [ ... ]
     },
     ...
}
```

## 2. As two separate props

``` js
columnDefs: [ ... ] // normal ColumnDef
columnGroups: [{title: "Group 1", colTags: [...]}, { ... }];
```

**Comment by shriniwasayyer14** [comment]
I would go with the latter separating the column defs and the column groups.

**Comment by erfangc** [comment]
Damn I was hoping you would go for the former. Lol.

The latter is easier to operate with though

**Comment by shriniwasayyer14** [comment]
The reason I said latter was because we might have the same columns within different groups. So we dont want to repeat the def for that column within each group. We could have it once within columnDefs and use the colTags in the columnGroups. Does that make sense ?

**Comment by erfangc** [comment]
That makes sense and is totally fine.

We have to consider the algorithm to sort the columns in order, and have a
conflict resolution mechanism in case the two sources specified conflicting
orders

**Comment by erfangc** [comment]
as of the last commit this is working in `master`, if you know how to setup TypeScript and jspm you can check out the example page
