### ISSUE TITLE
Write the API Documentation

### ISSUE THREAD

**Issue by erfangc** [erfangc/GigaGrid#18]
It should be easy given we are using TypeScript and can just take the main Props interface as our public API

However, it is worth noting that there should be ways to automatically generate documentation and it might be good to explore those ...

**Comment by arjshiv** [comment]
Started looking into https://www.npmjs.com/package/tsdoc and http://typedoc.io/ as two possible solutions

**Comment by erfangc** [comment]
I am excited! let me know how it goes! I am going to look at them more closely too ...

**Comment by erfangc** [comment]
done
